<<<<<<< HEAD
services:
  - type: web
    name: rentease-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    autoDeploy: true
=======
services:
  - type: web
    name: rentease-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    autoDeploy: true
>>>>>>> 55b0194c2d6ec825affe8c8a53a320b6496ad045
    healthCheckPath: /health 